# Generated by Django 4.2.7 on 2023-12-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviesmovie',
            options={'managed': False, 'ordering': ('name', 'year')},
        ),
    ]
